version: '3.7'
services:
  plugin:
    container_name: vale_docker
    restart: always
    build: ..
    volumes:
      - /run/docker/plugins:/run/docker/plugins
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/netmap:/dev/netmap
    network_mode: host
    pid: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_CHROOT
    stdin_open: true
    tty: true
    privileged: true
